### ISSUE TITLE
v1 bugs

### ISSUE THREAD

**Issue by sonnyvesali** [Nokhte/nokhte#247]
- [x] make sure that NOTHING inhibits deep links from being registered
         - I think implementing the architecture where if link is detected & acted upon immediately will help this issue 
- [x] remove multiple border glows (revert to previous architecture where they start holding immediately after, that’s really off, the pacing of these sessions usually isn’t like that
- [x] emojis don’t show in storage
- [x] things were duplicating also in storage
- [x] fix keyboard in notes phone
- [x] add deep link error handling to collaboration home
- [x] weird thing with not being able to swipe up after cross was tapped (simplify home screen phases)
- [x] Speak less smile more doesn’t show??
- [x] sessions should be shown in latest-first order
- [x] cover your ass both ways in terms of client & db duplication in storage
- [x] editing titles in storage if it’s too low

**Comment by sonnyvesali** [comment]
ok so for some reason deep links don't register IF they are initiated from before the login flow?? idk why

**Comment by soumivesali** [comment]
Great job **Wii Sports Voice**

**Comment by sonnyvesali** [comment]
Nintendo now owns your kids for your copyright infringement ©
