### ISSUE TITLE
Double Helix Design

### ISSUE THREAD

**Issue by soumivesali** [Nokhte/nokhte#63]
- [x] helix for 1 session
- [x] UI for multiple sessions w/ one person
- [ ] UI for multiple sessions w/ multiple people
- [x] How it looks like when they click on a particular helix piece
- [ ] How it looks like when they exit after clicking on a a particular helix piece
- [x] How it animates in 
- [ ] How you explain what the double helix represents
- [ ] Tutorial (if any) of going through one
- [ ] doing something with the sides (treat the pieces like disks)

**Comment by sonnyvesali** [comment]
[use this](https://youtube.com/watch?v=vqrmXhT2HQg) as a starting point for animating the disks
