### ISSUE TITLE
create the simplified one-talker-at-a-time v1

### ISSUE THREAD

**Issue by sonnyvesali** [Nokhte/nokhte#85]
so the rough list of things include:
- [x] simplifying the delete collaboration artifacts to just remove from active nokhte sessions
- [ ] metrics impl (posthog)
- [x] phase 0 for nokhte session (if any)
- [ ] the exit protocol

**Comment by sonnyvesali** [comment]
Are There Beginning Messages? => currently no so take out phase 1, and just have the hold to speak show up

**Comment by soumivesali** [comment]
@sonnyvesali 

We came to the conclusion that we have a conclusion. 

"To complete the call swipe up at the same time" (1st message)

"WAITING" (when one has swiped up an the other collaborator has not swiped up"

The "WAITING" screen will be a blurred screen as well.

**Comment by sonnyvesali** [comment]
to the moon brother

**Comment by soumivesali** [comment]
On our favourite rocketship.
